# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('colonia', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('longitud', models.CharField(max_length=240)),
                ('latitud', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHI', 'Chihuahua'), ('DIF', 'Ciudad de M\xe9xico'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'M\xe9xico'), ('MIC', 'Michoac\xe1n'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo Le\xf3n'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Quer\xe9taro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potos\xed'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucat\xe1n'), ('ZAC', 'Zacatecas')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=6, unique=True)),
                ('tag_radio', models.CharField(max_length=255)),
                ('modelo', models.CharField(default=True, max_length=250, null=True)),
                ('version_fw', models.CharField(default=True, max_length=250, null=True)),
                ('protocolo', models.CharField(default=True, max_length=250, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_unidad', models.BooleanField(default=True)),
                ('status_comunicacion_unidad', models.BooleanField(default=True)),
                ('status_conecxion', models.BooleanField(default=True)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unidades.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadConsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_consumo', models.CharField(max_length=60)),
                ('tag_unidad_consumo', models.CharField(max_length=255)),
                ('radio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unidades.Radio')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.Municipio'),
        ),
    ]
